services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: nick
            POSTGRES_DB: keep-music
        volumes:
            - keep-music-data:/var/lib/postgresql/data/
    redis:
        image: redis
        ports:
            - 6379:6379
volumes:
    keep-music-data:
